# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Docker Scout
description: List vulnerabilities in images; find better base images and upload an image SBOM to Docker Scout
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image:
    description: 'Image'
    required: false
  user: 
    description: 'Docker Hub User'
    required: true
  password: 
    description: 'Docker Hub Password/PAT'
    required: true
  registry_user: 
    description: 'Registry User'
    required: false
  registry_password: 
    description: 'Registry Password'
    required: false
  workspace: 
    description: 'Workspace ID'
    required: false
outputs:
  details:
    description: 'Detailed output'
  results:
    description: 'Result output'
  summary:
      description: 'Summary of results'
runs:
  using: docker
  image: docker://docker/scout-cli:latest
  env:
    DOCKER_SCOUT_HUB_USER: ${{ inputs.user }}
    DOCKER_SCOUT_HUB_PASSWORD: ${{ inputs.password }}
    DOCKER_SCOUT_WORKSPACE_ID: ${{ inputs.workspace }}
    DOCKER_SCOUT_REGISTRY_USER: ${{ inputs.registry_user }}
    DOCKER_SCOUT_REGISTRY_PASSWORD: ${{ inputs.registry_password }}
  entrypoint: /bin/sh
  args:
    - -c
    - >
      export EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64);
      /docker-scout cves ${{ inputs.image }} --only-fixed -o details.log;
      /docker-scout cves ${{ inputs.image }} -e --only-fixed --ignore-base -o out.log;
      exit_code=$?;
      /docker-scout quickview ${{ inputs.image }} -o summary.log; 
      echo 'summary<<' $EOF >> $GITHUB_OUTPUT;
      cat summary.log 2>/dev/null  >> $GITHUB_OUTPUT;
      echo $EOF >> $GITHUB_OUTPUT;
      echo 'details<<' $EOF >> $GITHUB_OUTPUT;
      cat details.log 2>/dev/null >> $GITHUB_OUTPUT;
      echo $EOF >> $GITHUB_OUTPUT;
      echo 'results<<' $EOF >> $GITHUB_OUTPUT;
      cat out.log 2>/dev/null >> $GITHUB_OUTPUT;
      echo $EOF >> $GITHUB_OUTPUT;
      exit $exit_code
